Adding docstring note.
mne-tools/mne-bids pull request #729
Opened 2021-03-15 14:41 UTC by adam2392

PR Description
--------------

Closes: #727 

I think those checks still should be applied to BIDs entities, but the suffix is allowed to be "overwritten".

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

2021-03-15 20:32 UTC, agramfort commented
CIs complain @adam2392 

can you see what's going on? thx

2021-03-15 23:16 UTC, adam2392 commented
https://4228-89170358-gh.circle-artifacts.com/0/dev/generated/mne_bids.BIDSPath.html#mne_bids.BIDSPath

2021-03-16 09:19 UTC, agramfort approved these changes
I'll let @hoechenberger merge if he's happy

2021-03-16 09:45 UTC, sappelhoff requested changes

2021-03-16 09:45 UTC, sappelhoff commented on mne_bids/path.py
> +                    _check_key_val(key, val)
Isn't this equivalent?

```suggestion
            if key == 'suffix' and not self.check:
                continue
            if val is not None and key != 'root':
                _check_key_val(key, val)
```

Looks much simpler to me

2021-03-16 11:42 UTC, hoechenberger commented on mne_bids/path.py
> +    and ``extension='.json'`` to the BIDSPath.
```suggestion
    To represent a filename such as ``dataset_description.json``,
    one can set ``check=False``, and pass ``suffix='dataset_description'``
    and ``extension='.json'``.
```

2021-03-16 11:45 UTC, hoechenberger commented on doc/whats_new.rst
> +- ``dataset_description.json`` file is now able to be represented as a ``BIDSPath``, by passing in ``check=False`` and ``suffix='dataset_description'``, by `Adam Li`_ (:gh:`729`)
```suggestion
- Arbitrary file names can now be represented as a `BIDSPath`` by passing the entire name as ``suffix`` and setting ``check=False``, by `Adam Li`_ (:gh:`729`)
```

2021-03-16 12:16 UTC, hoechenberger approved these changes
LGTM once we're green

2021-03-16 13:10 UTC, sappelhoff approved these changes

2021-03-16 13:17 UTC, agramfort commented
@adam2392 you have real CI failures apparently

2021-03-16 16:13 UTC, sappelhoff commented on mne_bids/path.py
> +                continue
```suggestion
                pass
                
```

2021-03-16 19:13 UTC, adam2392 commented
Shall I merge this then? (woot looks like I have squash and merge ability now :p)

2021-03-16 19:38 UTC, merged

2021-03-16 19:38 UTC, hoechenberger commented
Thanks, @adam2392!